// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qtpwtucdcytlmekwqcgb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0cHd0dWNkY3l0bG1la3dxY2diIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1ODQzODMsImV4cCI6MjA2NDE2MDM4M30.CHsJJRNN-tbLF_MUERMkfLPdCuh4BKMUrwmId60VsG0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);